# Dwar is configured once, in an initializer:
#
#   Dwar.configure do |config|
#     config.user_finder  = ->(query) { User.search(query) }
#     config.user_display = :display_name
#     config.admin_path   = "/admin/dwar"
#   end
#
# This file was generated by `bin/rails generate dwar:install`. Every option
# below is optional; the values shown are Dwar's defaults (see
# Dwar::Configuration). Uncomment and adjust what you need.

Dwar.configure do |config|
  # How the user picker looks up records to choose from. A callable that
  # accepts a query String and returns an enumerable of user records.
  # Default: nil (unset; required only when the picker endpoint is used)
  # config.user_finder = ->(query) { User.search(query) }

  # Method name used to render user picker labels.
  # Default: :to_s
  # config.user_display = :to_s

  # Path the engine mounts its admin UI at.
  # Default: "/dwar"
  # config.admin_path = "/dwar"

  # Gatekeeper for the admin UI: a callable evaluated with the controller;
  # nil means every request is denied.
  # Default: nil
  # config.authorization = ->(controller) { controller.current_user.admin? }

  # Whether flag evaluation results are cached.
  # Default: true
  # config.cache = true

  # How changes are attributed in the audit trail: a callable evaluated in
  # the admin controller context.
  # Default: nil
  # config.audit_actor = ->(controller) { controller.current_user }
end

# Mount the engine in config/routes.rb:
#   mount Dwar::Engine => "/dwar"
